@host = http://localhost
@port = 5142

@Restaurants.API_HostAddress = https://localhost:7217

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}}
Radom-Int: {{$randomInt}}

###

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/example

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"Jakub"

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?maxTemp=40&minTemp=0&qntResults=2

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/api/restaurant?id=1

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Tasty Bites",
    "Description": "A cozy Restaurant Serving a Variety of dishes.",
    "Category": "Italiasdaan",
    "ContactEmail": "info@tastybites.com",
    "ContactNumber": "555-1234",
    "City": "New York",
    "Street": "123 Main Street",
    "PostalCode": "10-001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1
Content-Type: application/json

{
    "Name": "Update Tasty Bites",
    "Description": "Update A cozy Restaurant Serving a Variety of dishes.",
   "HasDelivery": true
}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants/11/dishes
Content-Type: application/json

{
    "Name": "Pizza",
    "Description": "A delicious pizza with tomato sauce and cheese."
}

###
